name: Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # weekly

jobs:
  shellcheck:
    name: Shell Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'

  markdown:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Lint markdown
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.yml'
          args: '**/*.md'
